version: "4"

services:
    web:
        build: .
        port:
          - "5000:5000"
        volumes:
          - .:/code
        environment:
            FLASK_ENV: development
    redis:
        image: "redis:alpine"
